/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTimelisteRouteImport } from './routes/_authenticated/timeliste'
import { Route as AuthenticatedRapportRouteImport } from './routes/_authenticated/rapport'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedArbeidstyperRouteImport } from './routes/_authenticated/arbeidstyper'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimelisteRoute = AuthenticatedTimelisteRouteImport.update({
  id: '/timeliste',
  path: '/timeliste',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRapportRoute = AuthenticatedRapportRouteImport.update({
  id: '/rapport',
  path: '/rapport',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArbeidstyperRoute =
  AuthenticatedArbeidstyperRouteImport.update({
    id: '/arbeidstyper',
    path: '/arbeidstyper',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/arbeidstyper': typeof AuthenticatedArbeidstyperRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/rapport': typeof AuthenticatedRapportRoute
  '/timeliste': typeof AuthenticatedTimelisteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/arbeidstyper': typeof AuthenticatedArbeidstyperRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/rapport': typeof AuthenticatedRapportRoute
  '/timeliste': typeof AuthenticatedTimelisteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/arbeidstyper': typeof AuthenticatedArbeidstyperRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/rapport': typeof AuthenticatedRapportRoute
  '/_authenticated/timeliste': typeof AuthenticatedTimelisteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/arbeidstyper'
    | '/dashboard'
    | '/rapport'
    | '/timeliste'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/arbeidstyper' | '/dashboard' | '/rapport' | '/timeliste'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/arbeidstyper'
    | '/_authenticated/dashboard'
    | '/_authenticated/rapport'
    | '/_authenticated/timeliste'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/timeliste': {
      id: '/_authenticated/timeliste'
      path: '/timeliste'
      fullPath: '/timeliste'
      preLoaderRoute: typeof AuthenticatedTimelisteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapport': {
      id: '/_authenticated/rapport'
      path: '/rapport'
      fullPath: '/rapport'
      preLoaderRoute: typeof AuthenticatedRapportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arbeidstyper': {
      id: '/_authenticated/arbeidstyper'
      path: '/arbeidstyper'
      fullPath: '/arbeidstyper'
      preLoaderRoute: typeof AuthenticatedArbeidstyperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArbeidstyperRoute: typeof AuthenticatedArbeidstyperRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRapportRoute: typeof AuthenticatedRapportRoute
  AuthenticatedTimelisteRoute: typeof AuthenticatedTimelisteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArbeidstyperRoute: AuthenticatedArbeidstyperRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRapportRoute: AuthenticatedRapportRoute,
  AuthenticatedTimelisteRoute: AuthenticatedTimelisteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
