/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTimelisteRouteImport } from './routes/_authenticated/timeliste'
import { Route as AuthenticatedSatserRouteImport } from './routes/_authenticated/satser'
import { Route as AuthenticatedRapportRouteImport } from './routes/_authenticated/rapport'
import { Route as AuthenticatedProsjekterRouteImport } from './routes/_authenticated/prosjekter'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedArbeidstyperRouteImport } from './routes/_authenticated/arbeidstyper'
import { Route as AuthenticatedOrgsIndexRouteImport } from './routes/_authenticated/orgs/index'
import { Route as AuthenticatedOrgsOrgIdRouteRouteImport } from './routes/_authenticated/orgs/$orgId/route'
import { Route as AuthenticatedOrgsOrgIdIndexRouteImport } from './routes/_authenticated/orgs/$orgId/index'
import { Route as AuthenticatedOrgsOrgIdTimerRouteImport } from './routes/_authenticated/orgs/$orgId/timer'
import { Route as AuthenticatedOrgsOrgIdStartRouteImport } from './routes/_authenticated/orgs/$orgId/start'
import { Route as AuthenticatedOrgsOrgIdReportsRouteImport } from './routes/_authenticated/orgs/$orgId/reports'
import { Route as AuthenticatedOrgsOrgIdSettingsRatesRouteImport } from './routes/_authenticated/orgs/$orgId/settings.rates'
import { Route as AuthenticatedOrgsOrgIdSettingsProjectsRouteImport } from './routes/_authenticated/orgs/$orgId/settings.projects'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimelisteRoute = AuthenticatedTimelisteRouteImport.update({
  id: '/timeliste',
  path: '/timeliste',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSatserRoute = AuthenticatedSatserRouteImport.update({
  id: '/satser',
  path: '/satser',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRapportRoute = AuthenticatedRapportRouteImport.update({
  id: '/rapport',
  path: '/rapport',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProsjekterRoute = AuthenticatedProsjekterRouteImport.update({
  id: '/prosjekter',
  path: '/prosjekter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArbeidstyperRoute =
  AuthenticatedArbeidstyperRouteImport.update({
    id: '/arbeidstyper',
    path: '/arbeidstyper',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgsIndexRoute = AuthenticatedOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgsOrgIdRouteRoute =
  AuthenticatedOrgsOrgIdRouteRouteImport.update({
    id: '/orgs/$orgId',
    path: '/orgs/$orgId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgsOrgIdIndexRoute =
  AuthenticatedOrgsOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgsOrgIdRouteRoute,
  } as any)
const AuthenticatedOrgsOrgIdTimerRoute =
  AuthenticatedOrgsOrgIdTimerRouteImport.update({
    id: '/timer',
    path: '/timer',
    getParentRoute: () => AuthenticatedOrgsOrgIdRouteRoute,
  } as any)
const AuthenticatedOrgsOrgIdStartRoute =
  AuthenticatedOrgsOrgIdStartRouteImport.update({
    id: '/start',
    path: '/start',
    getParentRoute: () => AuthenticatedOrgsOrgIdRouteRoute,
  } as any)
const AuthenticatedOrgsOrgIdReportsRoute =
  AuthenticatedOrgsOrgIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedOrgsOrgIdRouteRoute,
  } as any)
const AuthenticatedOrgsOrgIdSettingsRatesRoute =
  AuthenticatedOrgsOrgIdSettingsRatesRouteImport.update({
    id: '/settings/rates',
    path: '/settings/rates',
    getParentRoute: () => AuthenticatedOrgsOrgIdRouteRoute,
  } as any)
const AuthenticatedOrgsOrgIdSettingsProjectsRoute =
  AuthenticatedOrgsOrgIdSettingsProjectsRouteImport.update({
    id: '/settings/projects',
    path: '/settings/projects',
    getParentRoute: () => AuthenticatedOrgsOrgIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/arbeidstyper': typeof AuthenticatedArbeidstyperRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/prosjekter': typeof AuthenticatedProsjekterRoute
  '/rapport': typeof AuthenticatedRapportRoute
  '/satser': typeof AuthenticatedSatserRoute
  '/timeliste': typeof AuthenticatedTimelisteRoute
  '/orgs/$orgId': typeof AuthenticatedOrgsOrgIdRouteRouteWithChildren
  '/orgs/': typeof AuthenticatedOrgsIndexRoute
  '/orgs/$orgId/reports': typeof AuthenticatedOrgsOrgIdReportsRoute
  '/orgs/$orgId/start': typeof AuthenticatedOrgsOrgIdStartRoute
  '/orgs/$orgId/timer': typeof AuthenticatedOrgsOrgIdTimerRoute
  '/orgs/$orgId/': typeof AuthenticatedOrgsOrgIdIndexRoute
  '/orgs/$orgId/settings/projects': typeof AuthenticatedOrgsOrgIdSettingsProjectsRoute
  '/orgs/$orgId/settings/rates': typeof AuthenticatedOrgsOrgIdSettingsRatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/arbeidstyper': typeof AuthenticatedArbeidstyperRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/prosjekter': typeof AuthenticatedProsjekterRoute
  '/rapport': typeof AuthenticatedRapportRoute
  '/satser': typeof AuthenticatedSatserRoute
  '/timeliste': typeof AuthenticatedTimelisteRoute
  '/orgs': typeof AuthenticatedOrgsIndexRoute
  '/orgs/$orgId/reports': typeof AuthenticatedOrgsOrgIdReportsRoute
  '/orgs/$orgId/start': typeof AuthenticatedOrgsOrgIdStartRoute
  '/orgs/$orgId/timer': typeof AuthenticatedOrgsOrgIdTimerRoute
  '/orgs/$orgId': typeof AuthenticatedOrgsOrgIdIndexRoute
  '/orgs/$orgId/settings/projects': typeof AuthenticatedOrgsOrgIdSettingsProjectsRoute
  '/orgs/$orgId/settings/rates': typeof AuthenticatedOrgsOrgIdSettingsRatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/arbeidstyper': typeof AuthenticatedArbeidstyperRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/prosjekter': typeof AuthenticatedProsjekterRoute
  '/_authenticated/rapport': typeof AuthenticatedRapportRoute
  '/_authenticated/satser': typeof AuthenticatedSatserRoute
  '/_authenticated/timeliste': typeof AuthenticatedTimelisteRoute
  '/_authenticated/orgs/$orgId': typeof AuthenticatedOrgsOrgIdRouteRouteWithChildren
  '/_authenticated/orgs/': typeof AuthenticatedOrgsIndexRoute
  '/_authenticated/orgs/$orgId/reports': typeof AuthenticatedOrgsOrgIdReportsRoute
  '/_authenticated/orgs/$orgId/start': typeof AuthenticatedOrgsOrgIdStartRoute
  '/_authenticated/orgs/$orgId/timer': typeof AuthenticatedOrgsOrgIdTimerRoute
  '/_authenticated/orgs/$orgId/': typeof AuthenticatedOrgsOrgIdIndexRoute
  '/_authenticated/orgs/$orgId/settings/projects': typeof AuthenticatedOrgsOrgIdSettingsProjectsRoute
  '/_authenticated/orgs/$orgId/settings/rates': typeof AuthenticatedOrgsOrgIdSettingsRatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/arbeidstyper'
    | '/dashboard'
    | '/prosjekter'
    | '/rapport'
    | '/satser'
    | '/timeliste'
    | '/orgs/$orgId'
    | '/orgs/'
    | '/orgs/$orgId/reports'
    | '/orgs/$orgId/start'
    | '/orgs/$orgId/timer'
    | '/orgs/$orgId/'
    | '/orgs/$orgId/settings/projects'
    | '/orgs/$orgId/settings/rates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/arbeidstyper'
    | '/dashboard'
    | '/prosjekter'
    | '/rapport'
    | '/satser'
    | '/timeliste'
    | '/orgs'
    | '/orgs/$orgId/reports'
    | '/orgs/$orgId/start'
    | '/orgs/$orgId/timer'
    | '/orgs/$orgId'
    | '/orgs/$orgId/settings/projects'
    | '/orgs/$orgId/settings/rates'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/arbeidstyper'
    | '/_authenticated/dashboard'
    | '/_authenticated/prosjekter'
    | '/_authenticated/rapport'
    | '/_authenticated/satser'
    | '/_authenticated/timeliste'
    | '/_authenticated/orgs/$orgId'
    | '/_authenticated/orgs/'
    | '/_authenticated/orgs/$orgId/reports'
    | '/_authenticated/orgs/$orgId/start'
    | '/_authenticated/orgs/$orgId/timer'
    | '/_authenticated/orgs/$orgId/'
    | '/_authenticated/orgs/$orgId/settings/projects'
    | '/_authenticated/orgs/$orgId/settings/rates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/timeliste': {
      id: '/_authenticated/timeliste'
      path: '/timeliste'
      fullPath: '/timeliste'
      preLoaderRoute: typeof AuthenticatedTimelisteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/satser': {
      id: '/_authenticated/satser'
      path: '/satser'
      fullPath: '/satser'
      preLoaderRoute: typeof AuthenticatedSatserRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapport': {
      id: '/_authenticated/rapport'
      path: '/rapport'
      fullPath: '/rapport'
      preLoaderRoute: typeof AuthenticatedRapportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prosjekter': {
      id: '/_authenticated/prosjekter'
      path: '/prosjekter'
      fullPath: '/prosjekter'
      preLoaderRoute: typeof AuthenticatedProsjekterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arbeidstyper': {
      id: '/_authenticated/arbeidstyper'
      path: '/arbeidstyper'
      fullPath: '/arbeidstyper'
      preLoaderRoute: typeof AuthenticatedArbeidstyperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orgs/': {
      id: '/_authenticated/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AuthenticatedOrgsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orgs/$orgId': {
      id: '/_authenticated/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orgs/$orgId/': {
      id: '/_authenticated/orgs/$orgId/'
      path: '/'
      fullPath: '/orgs/$orgId/'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRouteRoute
    }
    '/_authenticated/orgs/$orgId/timer': {
      id: '/_authenticated/orgs/$orgId/timer'
      path: '/timer'
      fullPath: '/orgs/$orgId/timer'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdTimerRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRouteRoute
    }
    '/_authenticated/orgs/$orgId/start': {
      id: '/_authenticated/orgs/$orgId/start'
      path: '/start'
      fullPath: '/orgs/$orgId/start'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdStartRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRouteRoute
    }
    '/_authenticated/orgs/$orgId/reports': {
      id: '/_authenticated/orgs/$orgId/reports'
      path: '/reports'
      fullPath: '/orgs/$orgId/reports'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdReportsRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRouteRoute
    }
    '/_authenticated/orgs/$orgId/settings/rates': {
      id: '/_authenticated/orgs/$orgId/settings/rates'
      path: '/settings/rates'
      fullPath: '/orgs/$orgId/settings/rates'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdSettingsRatesRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRouteRoute
    }
    '/_authenticated/orgs/$orgId/settings/projects': {
      id: '/_authenticated/orgs/$orgId/settings/projects'
      path: '/settings/projects'
      fullPath: '/orgs/$orgId/settings/projects'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdSettingsProjectsRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRouteRoute
    }
  }
}

interface AuthenticatedOrgsOrgIdRouteRouteChildren {
  AuthenticatedOrgsOrgIdReportsRoute: typeof AuthenticatedOrgsOrgIdReportsRoute
  AuthenticatedOrgsOrgIdStartRoute: typeof AuthenticatedOrgsOrgIdStartRoute
  AuthenticatedOrgsOrgIdTimerRoute: typeof AuthenticatedOrgsOrgIdTimerRoute
  AuthenticatedOrgsOrgIdIndexRoute: typeof AuthenticatedOrgsOrgIdIndexRoute
  AuthenticatedOrgsOrgIdSettingsProjectsRoute: typeof AuthenticatedOrgsOrgIdSettingsProjectsRoute
  AuthenticatedOrgsOrgIdSettingsRatesRoute: typeof AuthenticatedOrgsOrgIdSettingsRatesRoute
}

const AuthenticatedOrgsOrgIdRouteRouteChildren: AuthenticatedOrgsOrgIdRouteRouteChildren =
  {
    AuthenticatedOrgsOrgIdReportsRoute: AuthenticatedOrgsOrgIdReportsRoute,
    AuthenticatedOrgsOrgIdStartRoute: AuthenticatedOrgsOrgIdStartRoute,
    AuthenticatedOrgsOrgIdTimerRoute: AuthenticatedOrgsOrgIdTimerRoute,
    AuthenticatedOrgsOrgIdIndexRoute: AuthenticatedOrgsOrgIdIndexRoute,
    AuthenticatedOrgsOrgIdSettingsProjectsRoute:
      AuthenticatedOrgsOrgIdSettingsProjectsRoute,
    AuthenticatedOrgsOrgIdSettingsRatesRoute:
      AuthenticatedOrgsOrgIdSettingsRatesRoute,
  }

const AuthenticatedOrgsOrgIdRouteRouteWithChildren =
  AuthenticatedOrgsOrgIdRouteRoute._addFileChildren(
    AuthenticatedOrgsOrgIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArbeidstyperRoute: typeof AuthenticatedArbeidstyperRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProsjekterRoute: typeof AuthenticatedProsjekterRoute
  AuthenticatedRapportRoute: typeof AuthenticatedRapportRoute
  AuthenticatedSatserRoute: typeof AuthenticatedSatserRoute
  AuthenticatedTimelisteRoute: typeof AuthenticatedTimelisteRoute
  AuthenticatedOrgsOrgIdRouteRoute: typeof AuthenticatedOrgsOrgIdRouteRouteWithChildren
  AuthenticatedOrgsIndexRoute: typeof AuthenticatedOrgsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArbeidstyperRoute: AuthenticatedArbeidstyperRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProsjekterRoute: AuthenticatedProsjekterRoute,
  AuthenticatedRapportRoute: AuthenticatedRapportRoute,
  AuthenticatedSatserRoute: AuthenticatedSatserRoute,
  AuthenticatedTimelisteRoute: AuthenticatedTimelisteRoute,
  AuthenticatedOrgsOrgIdRouteRoute:
    AuthenticatedOrgsOrgIdRouteRouteWithChildren,
  AuthenticatedOrgsIndexRoute: AuthenticatedOrgsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
