/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOrgsIndexRouteImport } from './routes/_authenticated/orgs/index'
import { Route as AuthenticatedOrgsOrgIdRouteRouteImport } from './routes/_authenticated/orgs/$orgId/route'
import { Route as AuthenticatedOrgsOrgIdIndexRouteImport } from './routes/_authenticated/orgs/$orgId/index'
import { Route as AuthenticatedOrgsOrgIdTimerRouteImport } from './routes/_authenticated/orgs/$orgId/timer'
import { Route as AuthenticatedOrgsOrgIdStartRouteImport } from './routes/_authenticated/orgs/$orgId/start'
import { Route as AuthenticatedOrgsOrgIdReportsRouteImport } from './routes/_authenticated/orgs/$orgId/reports'
import { Route as AuthenticatedOrgsOrgIdRatesRouteImport } from './routes/_authenticated/orgs/$orgId/rates'
import { Route as AuthenticatedOrgsOrgIdProjectsRouteImport } from './routes/_authenticated/orgs/$orgId/projects'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgsIndexRoute = AuthenticatedOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgsOrgIdRouteRoute =
  AuthenticatedOrgsOrgIdRouteRouteImport.update({
    id: '/orgs/$orgId',
    path: '/orgs/$orgId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgsOrgIdIndexRoute =
  AuthenticatedOrgsOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgsOrgIdRouteRoute,
  } as any)
const AuthenticatedOrgsOrgIdTimerRoute =
  AuthenticatedOrgsOrgIdTimerRouteImport.update({
    id: '/timer',
    path: '/timer',
    getParentRoute: () => AuthenticatedOrgsOrgIdRouteRoute,
  } as any)
const AuthenticatedOrgsOrgIdStartRoute =
  AuthenticatedOrgsOrgIdStartRouteImport.update({
    id: '/start',
    path: '/start',
    getParentRoute: () => AuthenticatedOrgsOrgIdRouteRoute,
  } as any)
const AuthenticatedOrgsOrgIdReportsRoute =
  AuthenticatedOrgsOrgIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedOrgsOrgIdRouteRoute,
  } as any)
const AuthenticatedOrgsOrgIdRatesRoute =
  AuthenticatedOrgsOrgIdRatesRouteImport.update({
    id: '/rates',
    path: '/rates',
    getParentRoute: () => AuthenticatedOrgsOrgIdRouteRoute,
  } as any)
const AuthenticatedOrgsOrgIdProjectsRoute =
  AuthenticatedOrgsOrgIdProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedOrgsOrgIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/orgs/$orgId': typeof AuthenticatedOrgsOrgIdRouteRouteWithChildren
  '/orgs/': typeof AuthenticatedOrgsIndexRoute
  '/orgs/$orgId/projects': typeof AuthenticatedOrgsOrgIdProjectsRoute
  '/orgs/$orgId/rates': typeof AuthenticatedOrgsOrgIdRatesRoute
  '/orgs/$orgId/reports': typeof AuthenticatedOrgsOrgIdReportsRoute
  '/orgs/$orgId/start': typeof AuthenticatedOrgsOrgIdStartRoute
  '/orgs/$orgId/timer': typeof AuthenticatedOrgsOrgIdTimerRoute
  '/orgs/$orgId/': typeof AuthenticatedOrgsOrgIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/orgs': typeof AuthenticatedOrgsIndexRoute
  '/orgs/$orgId/projects': typeof AuthenticatedOrgsOrgIdProjectsRoute
  '/orgs/$orgId/rates': typeof AuthenticatedOrgsOrgIdRatesRoute
  '/orgs/$orgId/reports': typeof AuthenticatedOrgsOrgIdReportsRoute
  '/orgs/$orgId/start': typeof AuthenticatedOrgsOrgIdStartRoute
  '/orgs/$orgId/timer': typeof AuthenticatedOrgsOrgIdTimerRoute
  '/orgs/$orgId': typeof AuthenticatedOrgsOrgIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/orgs/$orgId': typeof AuthenticatedOrgsOrgIdRouteRouteWithChildren
  '/_authenticated/orgs/': typeof AuthenticatedOrgsIndexRoute
  '/_authenticated/orgs/$orgId/projects': typeof AuthenticatedOrgsOrgIdProjectsRoute
  '/_authenticated/orgs/$orgId/rates': typeof AuthenticatedOrgsOrgIdRatesRoute
  '/_authenticated/orgs/$orgId/reports': typeof AuthenticatedOrgsOrgIdReportsRoute
  '/_authenticated/orgs/$orgId/start': typeof AuthenticatedOrgsOrgIdStartRoute
  '/_authenticated/orgs/$orgId/timer': typeof AuthenticatedOrgsOrgIdTimerRoute
  '/_authenticated/orgs/$orgId/': typeof AuthenticatedOrgsOrgIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/orgs/$orgId'
    | '/orgs/'
    | '/orgs/$orgId/projects'
    | '/orgs/$orgId/rates'
    | '/orgs/$orgId/reports'
    | '/orgs/$orgId/start'
    | '/orgs/$orgId/timer'
    | '/orgs/$orgId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/orgs'
    | '/orgs/$orgId/projects'
    | '/orgs/$orgId/rates'
    | '/orgs/$orgId/reports'
    | '/orgs/$orgId/start'
    | '/orgs/$orgId/timer'
    | '/orgs/$orgId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/orgs/$orgId'
    | '/_authenticated/orgs/'
    | '/_authenticated/orgs/$orgId/projects'
    | '/_authenticated/orgs/$orgId/rates'
    | '/_authenticated/orgs/$orgId/reports'
    | '/_authenticated/orgs/$orgId/start'
    | '/_authenticated/orgs/$orgId/timer'
    | '/_authenticated/orgs/$orgId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orgs/': {
      id: '/_authenticated/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AuthenticatedOrgsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orgs/$orgId': {
      id: '/_authenticated/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orgs/$orgId/': {
      id: '/_authenticated/orgs/$orgId/'
      path: '/'
      fullPath: '/orgs/$orgId/'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRouteRoute
    }
    '/_authenticated/orgs/$orgId/timer': {
      id: '/_authenticated/orgs/$orgId/timer'
      path: '/timer'
      fullPath: '/orgs/$orgId/timer'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdTimerRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRouteRoute
    }
    '/_authenticated/orgs/$orgId/start': {
      id: '/_authenticated/orgs/$orgId/start'
      path: '/start'
      fullPath: '/orgs/$orgId/start'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdStartRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRouteRoute
    }
    '/_authenticated/orgs/$orgId/reports': {
      id: '/_authenticated/orgs/$orgId/reports'
      path: '/reports'
      fullPath: '/orgs/$orgId/reports'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdReportsRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRouteRoute
    }
    '/_authenticated/orgs/$orgId/rates': {
      id: '/_authenticated/orgs/$orgId/rates'
      path: '/rates'
      fullPath: '/orgs/$orgId/rates'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdRatesRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRouteRoute
    }
    '/_authenticated/orgs/$orgId/projects': {
      id: '/_authenticated/orgs/$orgId/projects'
      path: '/projects'
      fullPath: '/orgs/$orgId/projects'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdProjectsRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRouteRoute
    }
  }
}

interface AuthenticatedOrgsOrgIdRouteRouteChildren {
  AuthenticatedOrgsOrgIdProjectsRoute: typeof AuthenticatedOrgsOrgIdProjectsRoute
  AuthenticatedOrgsOrgIdRatesRoute: typeof AuthenticatedOrgsOrgIdRatesRoute
  AuthenticatedOrgsOrgIdReportsRoute: typeof AuthenticatedOrgsOrgIdReportsRoute
  AuthenticatedOrgsOrgIdStartRoute: typeof AuthenticatedOrgsOrgIdStartRoute
  AuthenticatedOrgsOrgIdTimerRoute: typeof AuthenticatedOrgsOrgIdTimerRoute
  AuthenticatedOrgsOrgIdIndexRoute: typeof AuthenticatedOrgsOrgIdIndexRoute
}

const AuthenticatedOrgsOrgIdRouteRouteChildren: AuthenticatedOrgsOrgIdRouteRouteChildren =
  {
    AuthenticatedOrgsOrgIdProjectsRoute: AuthenticatedOrgsOrgIdProjectsRoute,
    AuthenticatedOrgsOrgIdRatesRoute: AuthenticatedOrgsOrgIdRatesRoute,
    AuthenticatedOrgsOrgIdReportsRoute: AuthenticatedOrgsOrgIdReportsRoute,
    AuthenticatedOrgsOrgIdStartRoute: AuthenticatedOrgsOrgIdStartRoute,
    AuthenticatedOrgsOrgIdTimerRoute: AuthenticatedOrgsOrgIdTimerRoute,
    AuthenticatedOrgsOrgIdIndexRoute: AuthenticatedOrgsOrgIdIndexRoute,
  }

const AuthenticatedOrgsOrgIdRouteRouteWithChildren =
  AuthenticatedOrgsOrgIdRouteRoute._addFileChildren(
    AuthenticatedOrgsOrgIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrgsOrgIdRouteRoute: typeof AuthenticatedOrgsOrgIdRouteRouteWithChildren
  AuthenticatedOrgsIndexRoute: typeof AuthenticatedOrgsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrgsOrgIdRouteRoute:
    AuthenticatedOrgsOrgIdRouteRouteWithChildren,
  AuthenticatedOrgsIndexRoute: AuthenticatedOrgsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
